### PR TITLE
Add FrontMatterSearch component

### PR DESCRIPTION
**Pull request by danielbrzn**
Follows https://github.com/MarkBind/markbind/pull/175

This PR aims to add a FrontMatterSearch component to use the frontmatter data provided by `siteData.json`.

It will extend from the existing Typeahead component and will now be able to match user queries against keywords and titles.

It can be invoked with the following HTML snippet.

```html
<form class="navbar-form">
    <frontmattersearch :data="searchData" placeholder="Search" :on-hit="searchCallback"></frontmattersearch> 
</form>
```

### CODE REVIEW

**Comment by Gisonrg** [comment]
Haven't look at the code yet, but I wonder if we could avoid modifying the `Typehead.vue` directly. The current change will break its generalization and turns it into a very specific component with a specific type of input.
Instead, create a new composite Vue component that has a Typehead element inside, the new element will process the data and pass to the Typehead for rendering.
The benefit for composition is we can treat the `Typehead` element as a basic building block and uses it in other similar usage, e.g. another search box for searching only Terms used in the site.
Not sure how difficult it is to do the composite one, but please evaluate the idea and let us know if it can achieve the same purpose :P

**Comment by danielbrzn** [comment]
I understand the concern. I managed to create a new component `FrontMatterSearch.vue` that extends from the original `Typeahead.vue` with the custom logic required for using `siteData.json` as a search index.

Do let me know if there are any improvements that I could make 👍

**Comment by danielbrzn** [comment]
Woops! This isn't necessary anymore as @acjh managed to reverse-engineer the existing `Typeahead.vue` component to produce the same results as this `FrontMatterSearch.vue` component.

**Comment by Gisonrg** [comment]
Got it. Feel free to revert this :P

**Pull request merged**
