### PR TITLE
Support multiple inclusions of a modal #107

### PR DESCRIPTION
**Pull request by rachx**
Fixes https://github.com/MarkBind/markbind/issues/107

When there are multiple modals with the same id on one page, a trigger might incorrectly open multiple of them.

Before adding the trigger and event listener, check if the trigger has not been binded

### CODE REVIEW

**Comment by acjh** [comment]
Test not working:
1. Duplicate a Modal and its trigger in **modalDocs.vue**.
2. `npm run docs`
3. Clicking on one of the triggers results in 2 pop-ups.

**Comment by acjh** [comment]
Oh, I duplicated a Modal and its ~trigger~ button in **modalDocs.vue**.

```html
<button class="btn btn-default" v-show-modal="modal1">Show modal</button>
<modal title="==Modal title==" name="modal1">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</modal>
```

Your test case and the ones in **triggerDocs.vue** do work.

**Comment by acjh** [comment]
I see that [nus-cs2103/website-base](https://github.com/nus-cs2103/website-base) does not use the Vue syntax from **modalDocs.vue**.
The `<trigger for="modal:bugRepro">` syntax seems more intuitive and author-friendly.

@Gisonrg Shall we deprecate the Vue syntax and link to `#triggerDocs`? [`fe86dfe`](https://github.com/acjh/vue-strap/commit/fe86dfe42a32f4e1a1a8fd74df54ec78d18840eb)

>

**Comment by Gisonrg** [comment]
@acjh Yea we can deprecated that. Let's do it :) 

Please rebase this PR to resolve conflicts.

**Comment by rachx** [comment]
Rebased

**Pull request merged**
