### PR TITLE
Make popover and tooltip work for pure text on Mobile Safari

### PR DESCRIPTION
**Pull request by rachx**
Fixes https://github.com/MarkBind/markbind/issues/67

Currently, if the trigger is just a pure text, popovers and tooltip cannot be triggered/showed on Mobile Safari.
This is a documented Safari "bug" where click events are not fired on elements that are not typically interactive. One common workaround is to add a dummy "onclick=void(0)" to the element. (Hence, a dummy click event is added to the trigger).
However, the popover cannot be dismissed by clicking on surrounding non-interactive elements. I think it is likely for a user to try to click the popover itself so I added a dummy click event there to close the popover. 
Other suggestions?

Preview
[Popover pure text](https://rawgit.com/rachx/vue-strap/mobile-safari/#popover)
[Tooltip pure text](https://rawgit.com/rachx/vue-strap/mobile-safari/#tooltip)

### CODE REVIEW

**Comment by acjh** [comment]
Can you add a preview? You may refer to my previous PRs in this repo.

**Comment by acjh** [comment]
Works as advertised 👍

**Comment by acjh** [comment]
Regarding GitHub workflow, in the issue description:

- Can you replace "Addresses" in "Addresses MarkBind/markbind#67" with "[Fixes](https://help.github.com/articles/closing-issues-using-keywords/)"?
You can see if it works by checking for a dotted underline on the "Fixes" keyword.

**Comment by rachx** [comment]
Changed. No dotted line though

**Comment by Gisonrg** [comment]
Looks good. I think clicking on the popover should be ok for now :) Thanks!

**Comment by rachx** [comment]
Do I push the vue strap file to markbind cli?

**Comment by Gisonrg** [comment]
> Do I push the vue strap file to markbind cli?

Please do :)

**Pull request merged**
