### PR TITLE
Support tooltip indicator for italic text #100

### PR DESCRIPTION
**Pull request by rachx**
Fixes https://github.com/MarkBind/markbind/issues/100

[Underline preview](https://rawgit.com/rachx/vue-strap/tooltip-popover-underline/#popover)
I only updated the popover docs for this preview - will be reverted later)

### CODE REVIEW

**Comment by acjh** [comment]
@Gisonrg Was there a reason for using `border-bottom` instead of `text-decoration` initially?

**Comment by rachx** [comment]
I just checked the browser support. It doesn't seem to work on safari 😶

**Comment by Gisonrg** [comment]
> Was there a reason for using border-bottom instead of text-decoration initially?
Don't think so.

Will `-webkit-text-decoration` works on non-webkit browser? Like Firefox.

Btw, in your [preview](https://rawgit.com/rachx/vue-strap/tooltip-popover-underline/#popover) site, the `Trigger` session seems not functioning

**Comment by acjh** [comment]
> Will -webkit-text-decoration works on non-webkit browser? Like Firefox.

@rachx That doesn't seem to work on Chrome.

> Btw, in your preview site, the Trigger [section] seems not functioning

Triggers work fine on Chrome. On mobile Safari, only "Mouseenter" works ([as before](https://markbind.github.io/vue-strap/#popover)).

**Comment by rachx** [comment]
I tested - the normal `text-decoration` works on Chrome but not on mobile Safari.
The `-webkit-text-decoration` works on iPad but not on Chrome.

> Triggers work fine on Chrome. On mobile Safari, only "Mouseenter" works (as before).  

Is this a bug that is broken/not fixed by the previous PR?

**Comment by rachx** [comment]
I tried to use `text-decoration` so that it won't affect the styling of other elements. Maybe use both or either depending on the browser detected?

> Shall we stick to border-bottom?  

That works too.
For the underline to work for italic/bold elements, can we remove the `isPureText` check?

From the issue,
> pure text is easier to support styling with, and it is less complex to handle  

From testing with the vue strap docs, removing the check does not seem to affect the buttons. Are there other elements to check?

**Comment by acjh** [comment]
@Gisonrg Your input please :)

**Comment by Gisonrg** [comment]
> Maybe use both or either depending on the browser detected?

Seems like `text-decoration` would be more useful, as you said, `border` might affect other elements. I think we could either add `text-decoration` with all prefixes version (`-moz`, `-webkit`) or we could try if we could use other dynamically style binding other than just assign stuff to the `style` object [Vue.js doc on style](https://v1.vuejs.org/guide/class-and-style.html) as Vue should take care of the prefixing.

I am fine with removing pure text check, but make sure things don't break, and do add some notes to it in the document :)

Feel free to make a decision here and justify your choice :P

**Comment by rachx** [comment]
Tested and it works on Chrome, Mozilla and Mobile safari

**Comment by acjh** [comment]
Affects buttons:

**Comment by rachx** [comment]
Oh sorry, didn't notice. I will look into it again,
The other buttons are fine. These are generated with a `v-for`

**Comment by rachx** [comment]
Can you check again?

I did not use the inline css `v-bind:style` to add the text-decoration.
In the screenshot, the spacing of the buttons was affected. (Originally they were all glued together).
I think the styling should only be applied after later.

Instead, I added all possible prefixes (only 2) in `attached()` after checking with an autoprefixer.
It should works on Chrome, Mozilla and Mobile Safari.

**Comment by acjh** [comment]
Verified.

Related article: https://css-tricks.com/styling-underlines-web/

**Pull request closed without merging**
