### PR TITLE
Panels: give a 'collapse' button at the bottom of the panel #23

### PR DESCRIPTION
**Pull request by acjh**
Resolves MarkBind/markbind#23
Resolves MarkBind/markbind#104

[Preview](http://rawgit.com/acjh/vue-strap/23-panel-add-collapse-at-bottom/#accordion)

# Summary
- [x] Add 'collapse' button at bottom of panel
- [x] Add `bottom-switch` option — independent of `no-switch` option
- [x] Enable `bottom-switch` option by default, including for:
  - `<panel type="seamless">`
  - `dynamic-panel`
  - panels resulting from dynamic `include`
- [x] Only opaque on hover, else `opacity: 0.5`
- [x] Autoscroll to collapsed panel if its top is not in view

Related changes:
- [x] Add `builddocs` command for future reference in `README.md`
- [x] Add `bottom-switch` option to **Panel Options** in `accordionDocs.vue`
- [x] Make code and doc-code consistent in `accordionDocs.vue` and `dynamicPanelDocs.vue`

Known issue:
- The `panel` component is not aware of the fixed navbar so it gets blocked when scrolled into view.

### CODE REVIEW

**Comment by acjh** [comment]
@damithc Took a while for the preview - had to search my Terminal's history for `builddocs` command.

This is currently:
1. enabled for `panel` by default (respects the `no-switch` option)
1. disabled for `dynamic-panel` (has `no-switch` option by default)

I intend to add a `bottom-switch` option, which will override `no-switch` option.
Do you want the collapse button at the bottom to be enabled by default for both?

**Comment by damithc** [comment]
> Do you want the collapse button at the bottom to be enabled by default for both?

Yes, OK to have it by default for both. Even better if it can be made subtle (e.g. use grey unless hovering over it, or even show only on hover), but that part is not that important.

Also note that upon clicking this button the page should auto-scroll to the collapsed panel for this feature to be useful. When the user collapse a panel after reading it, he should be seeing the next panel immediately below the collapsed panel.

**Comment by acjh** [comment]
> Yes, OK to have it by default for both.

Will do.

> Even better if it can be made subtle (e.g. use grey unless hovering over it, or even show only on hover), but that part is not that important.

I shall see if it's possible to *use grey unless hovering over it* with css when I'm done with the later part. Suggest not to *show only on hover* as it hides a good feature, especially on mobile.

> Also note that upon clicking this button the page should auto-scroll to the collapsed panel for this feature to be useful. When the user collapse a panel after reading it, he should be seeing the next panel immediately below the collapsed panel.

Makes total sense - might take a while to implement.

**Comment by acjh** [comment]
> Also note that upon clicking this button the page should auto-scroll to the collapsed panel for this feature to be useful. When the user collapse a panel after reading it, he should be seeing the next panel immediately below the collapsed panel.

I used [`scrollIntoView`](https://github.com/acjh/vue-strap/blob/55a4839f2987053a53073123d9c8582c355b25f4/src/Panel.vue#L189-L191), but the `panel` component is not aware of the fixed navbar so it gets blocked.

**Comment by damithc** [comment]
Yes, navbar is a problem even when we use anchors to link to a specific place in the page. Not sure how to solve it. 
Ideally, autoscrolling should only happen if the top of the panel being collapsed is not already in view. 
Does this work for seamless panels too?

**Comment by acjh** [comment]
> Yes, navbar is a problem even when we use anchors to link to a specific place in the page. Not sure how to solve it.

I'll give it some thought.

> Ideally, autoscrolling should only happen if the top of the panel being collapsed is not already in view.

Will do.

> Does this work for seamless panels too?

Seems there is some other configuration to do. I'll only be able to work on this again after tomorrow.

**Comment by acjh** [comment]
@damithc I added a **Summary** in the PR description.

**Comment by damithc** [comment]
Looks good @acjh . Can try it out. @Gisonrg have a look if you have time.

**Comment by damithc** [comment]
BTW, @acjh can you do a release for me to try it out?

**Comment by acjh** [comment]
@damithc After clicking around the [CS2103 website](https://nus-cs2103.github.io/website) for a bit, I found the collapse button distracting.
I've added `margin-top: 5px` and reduced to `opacity: 0.2` for a better user experience - hopefully.

Before | After
--- | ---
Before | After

**Comment by damithc** [comment]
Yup, that looks better 👍 
Go ahead.

**Comment by damithc** [comment]
Let me know when the updated version is available.

**Comment by acjh** [comment]
Published: `npm i -g markbind-cli@1.4.1`

**Pull request merged**
